export enum DeveloperActionType {
    GET_ALL_DEVELOPERS_REQUEST = 'GET_ALL_DEVELOPERS_REQUEST',
    GET_ALL_DEVELOPERS_SUCCESS = 'GET_ALL_DEVELOPERS_SUCCESS',
    GET_ALL_DEVELOPERS_FAIL = 'GET_ALL_DEVELOPERS_FAIL',

    GET_DEVELOPER_REQUEST = 'GET_DEVELOPER_REQUEST',
    GET_DEVELOPER_SUCCESS = 'GET_DEVELOPER_SUCCESS',
    GET_DEVELOPER_FAIL = 'GET_DEVELOPER_FAIL',

    CREATE_DEVELOPER_REQUEST = 'CREATE_DEVELOPER_REQUEST',
    CREATE_DEVELOPER_SUCCESS = 'CREATE_DEVELOPER_SUCCESS',
    CREATE_DEVELOPER_FAIL = 'CREATE_DEVELOPER_FAIL',

    UPDATE_DEVELOPER_REQUEST = 'UPDATE_DEVELOPER_REQUEST',
    UPDATE_DEVELOPER_SUCCESS = 'UPDATE_DEVELOPER_SUCCESS',
    UPDATE_DEVELOPER_FAIL = 'UPDATE_DEVELOPER_FAIL',
}
