export enum FeatureActionType {
    GET_ALL_FEATURES_REQUEST = 'GET_ALL_FEATURES_REQUEST',
    GET_ALL_FEATURES_SUCCESS = 'GET_ALL_FEATURES_SUCCESS',
    GET_ALL_FEATURES_FAIL = 'GET_ALL_FEATURES_FAIL',

    GET_FEATURE_REQUEST = 'GET_FEATURE_REQUEST',
    GET_FEATURE_SUCCESS = 'GET_FEATURE_SUCCESS',
    GET_FEATURE_FAIL = 'GET_FEATURE_FAIL',

    CREATE_FEATURE_REQUEST = 'CREATE_FEATURE_REQUEST',
    CREATE_FEATURE_SUCCESS = 'CREATE_FEATURE_SUCCESS',
    CREATE_FEATURE_FAIL = 'CREATE_FEATURE_FAIL',

    UPDATE_FEATURE_REQUEST = 'UPDATE_FEATURE_REQUEST',
    UPDATE_FEATURE_SUCCESS = 'UPDATE_FEATURE_SUCCESS',
    UPDATE_FEATURE_FAIL = 'UPDATE_FEATURE_FAIL',
}
