export enum GameActionType {
    GET_ALL_GAMES_REQUEST = 'GET_ALL_GAMES_REQUEST',
    GET_ALL_GAMES_SUCCESS = 'GET_ALL_GAMES_SUCCESS',
    GET_ALL_GAMES_FAIL = 'GET_ALL_GAMES_FAIL',

    GET_GAME_REQUEST = 'GET_GAME_REQUEST',
    GET_GAME_SUCCESS = 'GET_GAME_SUCCESS',
    GET_GAME_FAIL = 'GET_GAME_FAIL',

    CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST',
    CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS',
    CREATE_GAME_FAIL = 'CREATE_GAME_FAIL',

    UPDATE_GAME_REQUEST = 'UPDATE_GAME_REQUEST',
    UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS',
    UPDATE_GAME_FAIL = 'UPDATE_GAME_FAIL',
}
