export enum GenreActionType {
    GET_ALL_GENRES_REQUEST = 'GET_ALL_GENRES_REQUEST',
    GET_ALL_GENRES_SUCCESS = 'GET_ALL_GENRES_SUCCESS',
    GET_ALL_GENRES_FAIL = 'GET_ALL_GENRES_FAIL',

    GET_GENRE_REQUEST = 'GET_GENRE_REQUEST',
    GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS',
    GET_GENRE_FAIL = 'GET_GENRE_FAIL',

    CREATE_GENRE_REQUEST = 'CREATE_GENRE_REQUEST',
    CREATE_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS',
    CREATE_GENRE_FAIL = 'CREATE_GENRE_FAIL',

    UPDATE_GENRE_REQUEST = 'UPDATE_GENRE_REQUEST',
    UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS',
    UPDATE_GENRE_FAIL = 'UPDATE_GENRE_FAIL',
}
