export enum PublisherActionType {
    GET_ALL_PUBLISHERS_REQUEST = 'GET_ALL_PUBLISHERS_REQUEST',
    GET_ALL_PUBLISHERS_SUCCESS = 'GET_ALL_PUBLISHERS_SUCCESS',
    GET_ALL_PUBLISHERS_FAIL = 'GET_ALL_PUBLISHERS_FAIL',

    GET_PUBLISHER_REQUEST = 'GET_PUBLISHER_REQUEST',
    GET_PUBLISHER_SUCCESS = 'GET_PUBLISHER_SUCCESS',
    GET_PUBLISHER_FAIL = 'GET_PUBLISHER_FAIL',

    CREATE_PUBLISHER_REQUEST = 'CREATE_PUBLISHER_REQUEST',
    CREATE_PUBLISHER_SUCCESS = 'CREATE_PUBLISHER_SUCCESS',
    CREATE_PUBLISHER_FAIL = 'CREATE_PUBLISHER_FAIL',

    UPDATE_PUBLISHER_REQUEST = 'UPDATE_PUBLISHER_REQUEST',
    UPDATE_PUBLISHER_SUCCESS = 'UPDATE_PUBLISHER_SUCCESS',
    UPDATE_PUBLISHER_FAIL = 'UPDATE_PUBLISHER_FAIL',
}
